APP_KEY = 'B%@~=ReieH6avGN%N9o4./RRvvY(o7uKqYPaRXeSrfo#0GdskZZ$TnpFre>R/c5:O:t~5n@O~UicGfuzWR.XE$9f#WPN(<K?NraKb3QnH*WM)0xP/YHi0.YOhYiO@a%q'
JWT_KEY = '9h8I=p8W5OnChcFkAJ=U>3$Y0%R9PsvYB.7XNqx6YY2pgQQC($F8|MyDe@w*9G#/n02cW1mHFMf6$m)O)gUoq#sH=I:yyFe)jiHVcZzPiPcaZ4c%NsMv<6Rh@KogBr=s'
MONGO_CLIENT_URL = 'mongodb://localhost:5000/'
MAIL_USERNAME = 'noreply.c3am.dev@gmail.com'
MAIL_PASSWORD = '4mrDDT7B>(=B'
AES_KEY = 'AAAAAAAAAAAAAAAA'
